#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Añade esto a tu bspwmrc
bspc rule -a Nm-connection-editor state=floating rectangle=400x500+0+0 center=true
bspc rule -a Blueman-manager state=floating rectangle=400x500+0+0 center=true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config border_width 0

# NOTE: Set your wallpaper path here or use an environment variable
# Default: $HOME/Pictures/wallpaper.png (change this to your preferred path)
WALLPAPER_PATH="${WALLPAPER_PATH:-$HOME/Pictures/wallpaper.png}"
/usr/bin/feh --bg-fill "$WALLPAPER_PATH" &
~/.config/polybar/./launch.sh &
picom &
blueman-applet &
nm-applet &
setxkbmap -option compose:ralt &
